# Generated by Django 5.2 on 2025-04-28 12:28

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[utils.validators.PhoneNumberValidator()]),
        ),
    ]
