# Generated by Django 5.2 on 2025-04-28 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_round', models.PositiveSmallIntegerField(default=0)),
                ('user1_point', models.PositiveSmallIntegerField(default=0)),
                ('user2_point', models.PositiveSmallIntegerField(default=0)),
                ('last_turn_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('current_user_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shown_categories', models.ManyToManyField(to='questions.category')),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_user_1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_as_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField()),
                ('is_user1_answered', models.BooleanField(default=False)),
                ('is_user2_answered', models.BooleanField(default=False)),
                ('user1_seen_time', models.DateTimeField(blank=True, null=True)),
                ('user2_seen_time', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('count_of_answered_question_by_user1', models.PositiveSmallIntegerField(default=0)),
                ('count_of_answered_question_by_user2', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.game')),
                ('questions', models.ManyToManyField(through='games.QuestionRound', to='questions.question')),
                ('selected_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.category')),
            ],
        ),
        migrations.AddField(
            model_name='questionround',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.round'),
        ),
    ]
