# Generated by Django 5.2 on 2025-04-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionRound',
            new_name='RoundQuestion',
        ),
    ]
