# Generated by Django 5.2 on 2025-04-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_questionround_roundquestion'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, through='games.RoundQuestion', to='questions.question'),
        ),
    ]
