# Generated by Django 5.2 on 2025-05-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_round_questions'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_round',
            new_name='current_round_number',
        ),
        migrations.AlterField(
            model_name='round',
            name='questions',
            field=models.ManyToManyField(through='games.RoundQuestion', to='questions.question'),
        ),
    ]
